import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { Pressable, StyleSheet } from 'react-native';

import { BrandGradient } from '@/theme/theme';

/**
 * Floating MishMesh AI assistant launcher — the live site's #inventory_chat_launcher at its
 * phone breakpoint (≤576px): a 56px brand-gradient circle 16px from the bottom/end edge with the
 * MishMesh image inside (/ai_assistance/static/images/missmesh.png, bundled as an asset).
 *
 * Tapping it toggles the MishMesh popup (see ./mishmesh-chat.tsx, which renders this button).
 *
 * Uses `end` rather than `right`: the live site's RTL (Arabic/Hebrew) stylesheet is generated by
 * flipping left/right, so the launcher sits on the left there.
 */
export function MishMeshButton({ onPress }: { onPress: () => void }) {
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [styles.launcher, pressed && styles.pressed]}
      accessibilityRole="button"
      accessibilityLabel="MishMesh">
      <LinearGradient
        colors={BrandGradient.colors}
        locations={BrandGradient.locations}
        // CSS 135deg.
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={styles.circle}>
        <Image
          source={require('@/assets/images/mishmesh.png')}
          style={styles.icon}
          contentFit="cover"
          accessibilityIgnoresInvertColors
        />
      </LinearGradient>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  launcher: {
    position: 'absolute',
    bottom: 16,
    end: 16,
    borderRadius: 28,
    // Live: box-shadow 0 18px 45px rgba(117, 52, 6, 0.32).
    shadowColor: 'rgb(117, 52, 6)',
    shadowOpacity: 0.32,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 18 },
    elevation: 10,
  },
  pressed: {
    opacity: 0.9,
  },
  circle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    width: 38,
    height: 38,
    borderRadius: 12,
  },
});
